export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
  },
  dashboard: '/dashboard/stats',
  employees: '/employees',
  employee: (id: string) => `/employees/${id}`,
  departments: '/departments',
  department: (id: string) => `/departments/${id}`,
  leave: '/leave',
  leaveItem: (id: string) => `/leave/${id}`,
  payroll: '/payroll/runs',
  payslips: '/payroll/payslips',
  performance: '/performance',
  jobs: '/recruitment/jobs',
  job: (id: string) => `/recruitment/jobs/${id}`,
  applicants: '/recruitment/applicants',
  attendance: '/attendance',
  benefits: '/benefits/plans',
  enrollments: '/benefits/enrollments',
  documents: '/documents',
  reports: '/reports',
  settings: '/settings',
  roles: '/settings/roles',
} as const
