export const queryKeys = {
  dashboard: ['dashboard'] as const,
  employees: (params?: Record<string, string>) => ['employees', params] as const,
  employee: (id: string) => ['employees', id] as const,
  departments: ['departments'] as const,
  department: (id: string) => ['departments', id] as const,
  leave: (params?: Record<string, string>) => ['leave', params] as const,
  payroll: ['payroll'] as const,
  payslips: ['payslips'] as const,
  performance: ['performance'] as const,
  jobs: ['jobs'] as const,
  applicants: (jobId?: string) => ['applicants', jobId] as const,
  attendance: (params?: Record<string, string>) => ['attendance', params] as const,
  benefits: ['benefits'] as const,
  enrollments: ['enrollments'] as const,
  documents: ['documents'] as const,
  reports: ['reports'] as const,
  settings: ['settings'] as const,
  roles: ['roles'] as const,
}
